# Generated by Django 3.0.8 on 2020-07-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameCategories',
            new_name='GameCategory',
        ),
        migrations.RenameModel(
            old_name='GameSeries',
            new_name='GameSerie',
        ),
    ]
