# Generated by Django 3.0.8 on 2020-07-26 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0002_auto_20200726_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_series',
            new_name='game_serie',
        ),
        migrations.RenameField(
            model_name='gamemode',
            old_name='game_rule',
            new_name='game_name',
        ),
        migrations.RenameField(
            model_name='gamerule',
            old_name='game_rule',
            new_name='game_name',
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent',
            field=models.ManyToManyField(default=None, null=True, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
    ]
