# Generated by Django 3.0.8 on 2020-07-26 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0003_auto_20200726_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opponent',
            field=models.ManyToManyField(default=None, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
    ]
