# Generated by Django 3.0.8 on 2020-07-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20200726_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='game_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Game', unique=True),
        ),
    ]
