# Generated by Django 3.0.8 on 2020-07-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20200726_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='game_mode_01',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='game_mode_02',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='game_mode_03',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='game_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Game', unique=True),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='rule_01',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='rule_02',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='rule_03',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
    ]
