# Generated by Django 3.0.8 on 2020-07-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_auto_20200726_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='mc_main_statistic',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
