# Generated by Django 3.0.8 on 2020-07-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20200726_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_mc_main_statistic',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_opp_main_statistic',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_winner',
            field=models.CharField(blank=True, choices=[(None, 'Informe o resultado da partida: '), ('WIN', 'Ganhei'), ('DRAW', 'Empatamos'), ('LOSE', 'Perdi')], default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='mc_opp_main_statistic',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='mc_print',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='matches_results/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp_main_statistic',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp_mc_main_statistic',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp_print',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='matches_results/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp_result',
            field=models.CharField(blank=True, choices=[(None, 'Informe o resultado da partida: '), ('WIN', 'Ganhei'), ('DRAW', 'Empatamos'), ('LOSE', 'Perdi')], default='', max_length=24, null=True),
        ),
    ]
