# Generated by Django 3.0.8 on 2020-07-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20200726_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_mode',
            field=models.CharField(blank=True, choices=[(None, 'Selecione um modo de jogo: '), ('ULTIMATE', 'Ultimate Team'), ('ELENCOS ONLINE', 'Elencos Online')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='match',
            name='game_rules',
            field=models.CharField(blank=True, choices=[(None, 'Selecione alguma regra: '), ('RULE_01', 'RULE_01'), ('RULE_02', 'RULE_02'), ('RULE_03', 'RULE_03')], default='', max_length=24),
        ),
    ]
