# Generated by Django 3.0.8 on 2020-07-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20200726_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='bet_value',
            field=models.IntegerField(choices=[(None, 'Informe o valor da aposta: '), (10, 'R$ 10,00'), (15, 'R$ 15,00'), (20, 'R$ 20,00'), (40, 'R$ 40,00'), (50, 'R$ 50,00')]),
        ),
    ]
