# Generated by Django 3.0.8 on 2020-07-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200711_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.ImageField(default='static/assets/images/default_user.png', upload_to='profile_picture/'),
        ),
    ]
