# Generated by Django 3.0.8 on 2020-07-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200711_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.ImageField(blank=True, default='static/assets/images/default_user.png', null=True, upload_to='profile_picture/'),
        ),
    ]
