# Generated by Django 3.0.8 on 2020-07-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200711_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rg',
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_digit',
            field=models.CharField(default=None, max_length=120, null=True, unique=True),
        ),
    ]
